package(default_visibility = ["//visibility:public"])

cc_test(
    name = "example_test",
    size = "small",
    srcs = ["example_test.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
