repos:
  - repo: local
    hooks:
      - id: format
        name: format staged files
        entry: ./tools/format.sh
        language: system
        pass_filenames: false
        always_run: true
