"""
Root build for all embedded software
"""

package(default_visibility = ["//visibility:public"])

# ============================================================================
# Example Blink Target
# ============================================================================

load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "blink_lib",
    hdrs = [
        "apps/blink/src/slate.hpp",
    ],
    includes = ["apps/blink/src"],
    deps = [
        "//common/cobs",
        "//common/utils",
        "//common/rust_example",
    ]
)

cc_binary(
    name = "blink",
    srcs = ["apps/blink/src/main.cpp"],
    includes = ["apps/blink/src"],
    copts = [
         "-Wall",
        "-Wextra",
        "-Werror",
        "-Wshadow",
        "-Wdouble-promotion",
        "-DCFG_TUD_CDC=2",
    ],
    deps = [
        ":blink_lib",
        "//proto:sats_command_nanopb",
        "@pico-sdk//src/rp2_common/pico_stdlib",
        "@pico-sdk//src/rp2_common/pico_stdio_usb",
    ],
)

