"""
Root build for all embedded software
"""

package(default_visibility = ["//visibility:public"])

# ============================================================================
# Example Blink Target
# ============================================================================

load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

EMBEDDED_WARNING_COPTS = [
    "-Wall",
    "-Wextra",
    "-Werror",
    "-Wshadow",
    "-Wdouble-promotion",
]

cc_library(
    name = "blink_lib",
    hdrs = ["apps/blink/src/slate.hpp"],
    includes = ["apps/blink/src"],
)

cc_binary(
    name = "blink",
    srcs = ["apps/blink/src/main.cpp"],
    includes = ["apps/blink/src"],
    copts = EMBEDDED_WARNING_COPTS,
    deps = [
        ":blink_lib",
        "@pico-sdk//src/rp2_common/pico_stdlib",
    ],
)

