[project]
name = "sats-monorepo"
version = "0.1.0"
description = "Monorepo for SSI satellites"
readme = "README.md"
authors = [
    { name = "Carson Lauer", email = "lauercarson@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pyelftools>=0.33",
    "pyserial>=3.5",
]

[project.scripts]
sats-monorepo = "sats_monorepo:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
