package(default_visibility = ["//visibility:public"])

load("@rules_rust//rust:defs.bzl", "rust_library", "rust_static_library")

cc_library(
    name = "rust_example",
    hdrs = ["example.h",],
    deps = [
        ":rust_static",
    ],
)
 

rust_static_library(
    name = "rust_static",
    srcs = ["example.rs"],
    edition = "2021",
    rustc_flags = [
        "-C", "panic=abort",
    ],
)
